### ISSUE TITLE
prepack script complains about missing chokidar dependency

### ISSUE THREAD

**Issue by BlackYoup** [CleverCloud/clever-components#187]
I'm not sure what I did wrong, I have this issue with both node 15 and 12. I tried to remove the node_modules folder but it didn't help. Installing the `chokidar` dependency using `npm install chokidar` worked fine.

```
clever-components on  addons-backups [!+] is 📦 v5.4.0 via ⬢ v12.18.2
❯ npm run prepack

> @clevercloud/components@5.4.0 prepack /home/arnaud/Dev/clevercloud/clever-components
> npm run test && npm run lint && npm run components:check-lit && npm run components:check-i18n && npm run components:build


> @clevercloud/components@5.4.0 test /home/arnaud/Dev/clevercloud/clever-components
> wtr 'test/**/*.test.*' --node-resolve

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'chokidar'
Require stack:
- /home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner-cli/node_modules/@web/test-runner-core/dist/server/TestRunnerServer.js
- /home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner-cli/node_modules/@web/test-runner-core/dist/runner/TestRunner.js
- /home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner-cli/node_modules/@web/test-runner-core/dist/index.js
- /home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner-cli/dist/startTestRunner.js
- /home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner-cli/dist/index.js
- /home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner/dist/startTestRunner.js
- /home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner/dist/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner-cli/node_modules/@web/test-runner-core/dist/server/TestRunnerServer.js:8:36)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner-cli/node_modules/@web/test-runner-core/dist/server/TestRunnerServer.js',
    '/home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner-cli/node_modules/@web/test-runner-core/dist/runner/TestRunner.js',
    '/home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner-cli/node_modules/@web/test-runner-core/dist/index.js',
    '/home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner-cli/dist/startTestRunner.js',
    '/home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner-cli/dist/index.js',
    '/home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner/dist/startTestRunner.js',
    '/home/arnaud/Dev/clevercloud/clever-components/node_modules/@web/test-runner/dist/bin.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @clevercloud/components@5.4.0 test: `wtr 'test/**/*.test.*' --node-resolve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @clevercloud/components@5.4.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arnaud/.npm/_logs/2020-12-28T14_54_45_204Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @clevercloud/components@5.4.0 prepack: `npm run test && npm run lint && npm run components:check-lit && npm run components:check-i18n && npm run components:build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @clevercloud/components@5.4.0 prepack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/arnaud/.npm/_logs/2020-12-28T14_54_45_222Z-debug.log
```

**Comment by hsablonniere** [comment]
Not sure about the details but fixed by 1a1b3c7bc955cac28754af2520db8a3f3d6736d0
